export const SEARCH_POKEMON = Object.freeze({
  NONE: "POKEMON_NONE",
  INIT: "POKEMON_SEARCH",
  FOUND: "POKEMON_FOUND",
  SPECIES_FOUND: "POKEMON_SPECIES_FOUND",
  MOVES_FOUND: "POKEMON_ABILITIES_FOUND",
  DONE: "POKEMON_SEARCH_COMPLETE",
  FAILED: "POKEMON_SEARCH_FAILED"
});

export const ADD_FAVOURITE = "ADD_FAVOURITE";
